version: '3'

services:
  weather-app__back-end:
    build: ./weather-app__back-end
    ports:
      - 3000:3000

  weather-app__front-end:
    build: ./weather-app__front-end
    ports:
      - 80:80
    depends_on:
      - weather-app__back-end